# Generated by Django 2.2.19 on 2021-12-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211223_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
